CAC/cac_settings/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib import auth
from django.urls import path, include
from django.conf.urls import url

import store, dash
from store.views import index

urlpatterns = [
    url(r'^', include(('store.urls', 'store'), namespace="store")),
]

CAC/store/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search', views.search, name='search'),
    url(r'^items/(?P<item_id>[0-9]+)/$', views.item_detail, name='items'),
    url(r'^add_to_cart/', views.add_to_cart, name='add_to_cart'),
    url(r'^remove_from_cart/', views.remove_from_cart, name='remove_from_cart'),
    url(r'^reset_session/', views.reset_session, name='reset_session'),
    url(r'^checkout/', views.checkout, name='checkout'),
    url(r'^confirmed/', views.confirmed, name="confirmed"),
]

CAC/dash/models.py
from django.db import models

# Create your models here.

CAC/store/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Ptxt(models.Model):

    name = models.CharField(max_length=10)
    txt  = models.CharField(max_length=4500)
    page = models.CharField(max_length=20)

class Item(models.Model):

    name        = models.CharField(max_length=15)
    img_one     = models.CharField(max_length=100, null=True)
    img_two     = models.CharField(max_length=100, null=True)
    img_three   = models.CharField(max_length=100, null=True)
    img_four    = models.CharField(max_length=100, null=True)
    img_five    = models.CharField(max_length=100, null=True)
    price       = models.FloatField()
    rate        = models.IntegerField(default=1)
    reduc       = models.IntegerField(null=True)
    category    = models.CharField(max_length=25, null=True)

    new       = models.BooleanField(default=True)
    available = models.BooleanField(default=True)

    def serialize(self):
        return self.__dict__


class Order(models.Model):

    sid = models.CharField(max_length=50, unique=True)
    order = models.IntegerField(unique=True, primary_key=True)
    file = models.CharField(max_length=80, unique=True)

CAC/dash/views.py
from django.shortcuts import render

CAC/store/views.py
from django.shortcuts import render
from django.http import HttpResponse
from os import getcwd
import random

from store.misc import *
from store.models import Item
from store.forecastPurge.forecastAPI import purge

# Create your views here.
def index(request):
    p_index = Page('index')

    context = {
        'items'   : p_index.all_items(),
        'ptxt'    : p_index.txts,
        'errors'  : [],
    }

    try:
        context['cart'] = request.session['cart']

    except:
        context['cart'] = []

    return render(request, 'store/item.html', context)


def listing(request, opt=None):
    p_listing = Page('listing')

    context = {
        'ptxt'          : p_listing.txts,
        'items'         : p_listing.all_items(),
        "errors"        : []
    }

    try:
        context['cart'] = request.session['cart']

    except:
        context['cart'] = []

    if opt:
        context['errors'].append(opt)

    return render(request, 'store/search.html', context)

def search(request):

    query = request.GET.get('query')
    p_search = Page('search')

    if not query:
        return listing(request)

    else:
        items = p_search.search(query)


    if items == []:
        return listing(request, opt="No result for {}.".format(query))

    context = {
                'ptxt'          : p_search.txts,
                'items'         : items,
                "errors"        : []
            }

    try:
        context['cart'] = request.session['cart']

    except:
        context['cart'] = []

    else:
        
        return render(request, 'store/search.html', context )

def item_detail(request, item_id):

    try:
        item = Item.objects.get(id=item_id)

    except:
        return render(request, 'store/404.html')


    context = {
        'ptxt'          : Page('item_detail').txts,
        'item'          : item,
        "errors"        : []
    }  

    try:
        context['cart'] = request.session['cart']

    except:
        context['cart'] = []
        
    return render(request, 'store/item_detail.html', context)


def add_to_cart(request):

    if request.method == "POST":
        items = request.POST.items()
        HttpResponse.status_code = 201

        for key, value in items:
            if key != 'csrfmiddlewaretoken':
                item = Item.objects.get(id=value)

        try:
            cart = Cart(request.session['cart'])
        except:
            cart = Cart([])

        cart.add_item(item)
        request.session['cart'] = cart.raw

        return HttpResponse()

    else:

        return render(request, 'store/400.html')

def remove_from_cart(request):

    if request.method == "POST":
        id = request.POST.get('id')
        HttpResponse.status_code = 201
        
        cart = Cart(request.session['cart'])
        cart.remove_item(id)

        print(cart.raw)

        request.session['cart'] = cart.raw

    return HttpResponse()

def reset_session(request):
    purge()
    try:
        o = Order.objects.get(sid=request.session._session_key)
        delete_order(o)
    except:
        pass
    request.session.clear()
    return HttpResponse()

def checkout(request):

    context = {
        'ptxt'          : Page('checkout_detail').txts,
        "errors"        : []
    }

    if request.method == "POST" and not no_order(request):
        confirmed(request)

    if request.method == "POST" and no_order(request):

        if easy_antispam(request):
            order = cart_dump({
                'items' : request.session['cart'],
                'sid'   : request.session._session_key
                })
            del request.session['cart']
            context['order'] = order

            return render(request, 'store/confirmed.html', context)

        else:
            context['errors'].append('antispam')
            return render(request, 'store/checkout.html', context)

    elif request.method == "GET":
        try:
            context['cart'] = request.session['cart']
        except:
            context['cart'] = []
        return render(request, 'store/checkout.html', context)
    else:
        return render(request, 'store/404.html')

def confirmed(request):
    o = Order.objects.get(sid=request.session._session_key)

    context = {
        'ptxt'          : Page('Confirmed').txts,
        "errors"        : [],
        'order'         : order_load(o.id),
    }


    return render(request, 'store/confirmed.html', context)

CAC/store/templates/store/index.html
{% extends 'store/nav.html' %}
{% block content %}
  <!-- Intro -->
  <section>

    <!-- Carousel Wrapper -->
    <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

      <!-- Indicators -->
      <ol class="carousel-indicators">

        <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>

        <li data-target="#carousel-example-1z" data-slide-to="1"></li>

        <li data-target="#carousel-example-1z" data-slide-to="2"></li>

      </ol>
      <!-- Indicators -->

      <!-- Slides -->
      <div class="carousel-inner" role="listbox">

        <!-- First slide -->
        <div class="carousel-item active">

          <div class="view h-100">

            <img class="d-block h-100 w-lg-100" src="https://mdbootstrap.com/img/Photos/Others/ecommerce4.jpg"
              alt="First slide">

            <div class="mask">

              <!-- Caption -->
              <div class="full-bg-img flex-center white-text">

                <ul class="animated fadeIn col-10 list-unstyled">

                  <li>

                    <p class="h1 red-text mb-4 mt-5">

                      <strong>Sale off 30% on every saturday!</strong>

                    </p>

                  </li>

                  <li>

                    <h5 class="h5-responsive dark-grey-text font-weight-bold mb-5">Tempora incidunt ut labore et dolore

                      veritatis et quasi architecto beatae</h5>

                  </li>

                  <li>

                    <a target="_blank" href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
                      class="btn btn-danger btn-rounded" rel="nofollow">See more!</a>

                  </li>

                </ul>

              </div>
              <!-- Caption -->

            </div>

          </div>

        </div>
        <!-- First slide -->

        <!-- Second slide -->
        <div class="carousel-item h-100">

          <div class="view h-100">

            <img class="d-block h-100 w-lg-100" src="https://mdbootstrap.com/img/Photos/Others/ecommerce2.jpg"
              alt="Second slide">

            <div class="mask">

              <!-- Caption -->
              <div class="full-bg-img flex-center white-text">

                <ul class="animated fadeIn col-10 list-unstyled">

                  <li>

                    <p class="h1 dark-grey-text mb-4">

                      <strong>Nemo enim ipsam voluptatem quia voluptas</strong>

                    </p>

                  </li>

                  <li>

                    <h5 class="h5-responsive dark-grey-text font-weight-bold mb-5">Tempora incidunt ut labore et dolore

                      veritatis et quasi architecto beatae</h5>

                  </li>

                  <li>

                    <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/"
                      class="btn btn-primary btn-rounded" rel="nofollow">Read more</a>

                  </li>

                </ul>

              </div>
              <!-- Caption -->

            </div>

          </div>

        </div>
        <!-- Second slide -->

        <!-- Third slide -->
        <div class="carousel-item">

          <div class="view h-100">

            <img class="d-block h-100 w-lg-100" src="https://mdbootstrap.com/img/Photos/Others/ecommerce3.jpg"
              alt="Third slide">

            <div class="mask">

              <!-- Caption -->
              <div class="full-bg-img flex-center white-text">

                <ul class="animated fadeIn col-md-10 text-center text-md-right list-unstyled">

                  <li>

                    <p class="h1 blue-text mb-4 mt-5 pr-lg-5">

                      <strong>Sale off 20% on every headphones!</strong>

                    </p>

                  </li>

                  <li>

                    <h5 class="h5-responsive dark-grey-text font-weight-bold mb-5 pr-lg-5">Tempora incidunt ut labore et

                      dolore veritatis et quasi</h5>

                  </li>

                </ul>

              </div>
              <!-- Caption -->

            </div>

          </div>

        </div>
        <!-- Third slide -->

      <!-- Controls -->
      <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">

        <span class="carousel-control-prev-icon" aria-hidden="true"></span>

        <span class="sr-only">Previous</span>

      </a>

      <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">

        <span class="carousel-control-next-icon" aria-hidden="true"></span>

        <span class="sr-only">Next</span>

      </a>
      <!-- Controls -->

    </div>


    </div>

  </section>
  <!-- Intro -->

  <!-- Main Container -->
  <div class="container">

    <!-- Grid row -->
    <div class="row pt-4">

      <!-- Content -->
      <div class="col-lg-12">        

        <!-- Section: Advertising -->
        <section>

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="col-12">

              <!-- Image -->
              <div class="view  z-depth-1">

                <img src="https://mdbootstrap.com/img/Photos/Others/ecommerce5.jpg" class="img-fluid"
                  alt="sample image">

                <div class="mask rgba-stylish-slight">

                  <div class="dark-grey-text text-right pt-lg-5 pt-md-1 mr-5 pr-md-4 pr-0">

                    <div>

                      <a>

                        <span class="badge badge-primary">SALE</span>

                      </a>

                      <h2 class="card-title font-weight-bold pt-md-3 pt-1">

                        <strong>Sale from 20% to 50% on every tablet!

                        </strong>

                      </h2>

                      <p class="pb-lg-3 pb-md-1 clearfix d-none d-md-block">Lorem ipsum dolor sit amet, consectetur

                        adipisicing elit. </p>

                      <a class="btn mr-0 btn-primary btn-rounded clearfix d-none d-md-inline-block">Read more</a>

                    </div>

                  </div>

                </div>

              </div>
              <!-- Image -->

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </section>
        <!-- Section: Advertising -->
        </div>

        <!-- Section: Last items -->
        <section>

          <hr class="mb-5">

          <!-- Grid row -->
          <div class="row">


            {% for item in items %}
              <!-- Grid column -->
              {% if forloop.counter <= 8 %}
                <div id="item-{{ forloop.counter }}" class="col-lg-3 col-md-6 mb-4 show">

                <!-- Card -->
                <div class="card card-ecommerce">
                  <!-- Card image -->
                  <div class="view overlay">
                    <img src="{{ item.img_one }}" class="img-fluid"
                      alt="sample image">

                    <a href="{% url 'store:items' item_id=item.id %}">
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>
                  <!-- Card image -->

                  <!-- Card content -->
                  <div class="card-body">
                    <!-- Category & Title -->
                    <h5 class="card-title mb-1">
                      <strong>
                        <a href="{% url 'store:items' item_id=item.id %}"
                         id="{{item.id}}-name" class="dark-grey-text">{{ item.name }}</a>
                      </strong>
                    </h5>

                    {% if item.available %}
                    <span class="badge badge-danger mb-2">Displonible</span>
                    {% endif %}

                    <!-- Rating -->
                    <ul class="rating">
                      {% for i in '12345'|make_list %}
                        {% if item.rate >= forloop.counter %}
                          <li>
                            <i class="fas fa-star blue-text"></i>
                          </li>
                        {% else %}
                          <li>
                            <i class="fas fa-star grey-text"></i>
                          </li>
                          {% endif %}
                          {% endfor %}
                    </ul>

                    <!-- Card footer -->
                    <div class="card-footer pb-0">
                      <div class="row mb-0">
                        <span class="float-left">
                          <strong id="{{item.id}}-price">{{ item.price }}</strong><strong>$</strong>
                        </span>

                        <span class="float-right">
                          <a onclick="add_to_cart('{{item.id}}', '{{csrf_token}}')"
                             data-toggle="tooltip" data-placement="top" title="Add to Cart">
                            <i class="fas fa-shopping-cart ml-3"></i>
                          </a>
                        </span>
                      </div>
                    </div>
                  </div>
                  <!-- Card content -->
                </div>
                <!-- Card -->
              </div>
              {% endif %}
              <!-- Grid column -->
            {% endfor %}

          </div>
          <!-- Grid row -->

          <!-- Grid row -->
          <div class="row justify-content-center mb-4">

            <a href="/search/" class="btn btn-outline-blue">Voir tout</a>

          </div>
          <!-- Grid row -->

        </section>
        <!-- Section: Last items -->

      </div>
      <!-- Content -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Main Container -->

  {% endblock %}

CAC/store/templates/store/nav.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>DTA</title>
  {% load static %}
  <!-- MDB icon -->
  <link rel="icon" href="{% static 'store/img/mdb-favicon.ico' %}" type="image/x-icon">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{% static 'store/css/bootstrap.min.css' %}">
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'store/css/mdb.min.css' %}">
  <!-- Your custom styles (optional) -->
  <link rel="stylesheet" href="{% static 'store/css/dash.css' %}">
  <link rel="stylesheet" href="{% static 'store/css/style.css' %}">
</head>

<body class="homepage-v1 hidden-sn white-skin animated">
  {% csrf_token %}
      <!-- Navbar -->
      <nav class="navbar fixed-top navbar-expand-lg  scrolling-navbar ">
        
        <div class="container">
          <a class="navbar-brand font-weight-bold" href="/">
            <strong>SHOP</strong>
          </a>

          <form class="search-form" role="search" action="{% url 'store:search' %}" method="GET">
              <input name="query" id="browse_field" type="text" class="form-control" placeholder="Search">
          </form>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4"
            aria-controls="navbarSupportedContent-4" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link waves-effect waves-light dark-grey-text font-weight-bold" href="#">
                  <i class="fas fa-envelope blue-text"></i> Contact
                  <span class="sr-only">(current)</span>
                </a>
              </li>

              <li class="nav-item ">
                <a class="nav-link dark-grey-text font-weight-bold" href="#" data-toggle="modal"
                  data-target="#cart-modal-ex">
                  <span id="item-cart-counter" class="badge danger-color">4</span>
                  <i class="fas fa-shopping-cart blue-text" aria-hidden="true"></i>
                  <span class="clearfix d-none d-sm-inline-block">Cart</span>
                </a>
              </li>

            </ul>
          </div>
        </div>
      </nav>
      <!-- Navbar -->
  
    </header>
    <!-- Navigation -->

    <!-- Cart Modal -->
  <div class="modal fade cart-modal" id="cart-modal-ex" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
  aria-hidden="true">

  <div class="modal-dialog" role="document">

    <!-- Content -->
    <div class="modal-content">

      <!-- Header -->
      <div class="modal-header">

        <h4 class="modal-title font-weight-bold dark-grey-text" id="myModalLabel">Your cart</h4>

        <button type="button" class="close" data-dismiss="modal" aria-label="Close">

          <span aria-hidden="true">&times;</span>

        </button>

      </div>

      <!-- Body -->
      <div class="modal-body">

        {% if cart %}
        <table id="table-cart" class="table table-hover">
        {% else %}
        <table id="table-cart" class="table table-hover hidden">
        <div id="empty" class="container-fluid align-center">
          <p>Your cart is empty yet.</p>
        </div>
        {% endif %}
          <thead>
            <tr>
              <th>Product name</th>
              <th>Price</th>
              <th>Quantity</th>
              <th></th>
            </tr>

          </thead>

          <tbody id="cart-tbody">

            {% for itm in cart %}
            <tr id="tr-{{itm.id}}">
              <td>{{itm.name}}</td>
              <td>{{itm.price}}$</td>
              <td class="tcount" id="nbr-{{itm.id}}">{{itm.nbr}}</td>
              <td>
                <a onclick="remove_from_cart('{{itm.id}}', '{{csrf_token}}')">
                  <i class="fas fa-eraser"></i>
                </a>
              </td>
            </tr>
            {% endfor %}

          </tbody>
        </table>

        <a href="/checkout/">
          <button href="/checkout/" class="btn btn-primary btn-rounded btn-sm">Checkout</button>
        </a>
      </div>

      <!-- Footer -->
    </div>
    <!-- Content -->
  </div>
</div>
<!-- Cart Modal -->

    {% block content %}
    {% endblock %}

  <!-- Footer -->
  <footer class="page-footer text-center text-md-left stylish-color-dark pt-0">
    <div style="background-color: #4285f4;">
      <div class="container">
        <!-- Grid row -->
        <div class="row py-4 d-flex align-items-center">
          <!-- Grid column -->
          <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
            <h6 class="mb-0 white-text">Get connected with us on social networks!</h6>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-6 col-lg-7 text-center text-md-right">
            <!-- Facebook -->
            <a class="fb-ic ml-0 px-2">
              <i class="fab fa-facebook-f white-text"> </i>
            </a>
            <!-- Twitter -->
            <a class="tw-ic px-2">
              <i class="fab fa-twitter white-text"> </i>
            </a>
            <!-- Google + -->
            <a class="gplus-ic px-2">
              <i class="fab fa-google-plus-g white-text"> </i>
            </a>

            <!-- Linkedin -->
            <a class="li-ic px-2">
              <i class="fab fa-linkedin-in white-text"> </i>
            </a>
            <!-- Instagram -->
            <a class="ins-ic px-2">
              <i class="fab fa-instagram white-text"> </i>
            </a>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </div>

    <!-- Footer Links -->
    <div class="container mt-5 mb-4 text-center text-md-left">
      <div class="row mt-3">
        <!-- First column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mb-4">
          <h6 class="text-uppercase font-weight-bold">
            <strong>Company name</strong>
          </h6>
          <hr class="blue mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>Here you can use rows and columns here to organize your footer content. Lorem ipsum dolor sit amet,
            consectetur
            adipisicing elit.</p>
        </div>
        <!-- First column -->
        <!-- Second column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <h6 class="text-uppercase font-weight-bold">
            <strong>Products</strong>
          </h6>
          <hr class="blue mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
          <p>
            <a href="#!">MDBootstrap</a>
          </p>
          <p>
            <a href="#!">MDWordPress</a>
          </p>
          <p>
            <a href="#!">BrandFlow</a>
          </p>
          <p>
            <a href="#!">Bootstrap Angular</a>
          </p>
        </div>
        <!-- Second column -->

        <!-- Third column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

          <h6 class="text-uppercase font-weight-bold">

            <strong>Useful links</strong>

          </h6>

          <hr class="blue mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">

          <p>

            <a href="#!">Your Account</a>

          </p>

          <p>

            <a href="#!">Become an Affiliate</a>

          </p>

          <p>

            <a href="#!">Shipping Rates</a>

          </p>

          <p>

            <a href="#!">Help</a>

          </p>

        </div>
        <!-- Third column -->

        <!-- Fourth column -->
        <div class="col-md-4 col-lg-3 col-xl-3">

          <h6 class="text-uppercase font-weight-bold">

            <strong>Contact</strong>

          </h6>

          <hr class="blue mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">

          <p>

            <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>

          <p>

            <i class="fas fa-envelope mr-3"></i> info@example.com</p>

          <p>

            <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>

          <p>

            <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

        </div>
        <!-- Fourth column -->

      </div>

    </div>
    <!-- Footer Links -->

    <!-- Copyright -->
    <div class="footer-copyright py-3 text-center">

      <div class="container-fluid">

        © 2019 Copyright: <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>

      </div>

    </div>
    <!-- Copyright -->

  </footer>
  <!-- Footer -->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'store/js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'store/js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'store/js/bootstrap.min.js' %}">
  </script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'store/js/mdb-4.8.11.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'store/js/click.js' %}"></script>
  <script>
    const csrf = '{{csrf_token}}';
  </script>

</body>

</html>

CAC/store/templates/store/search.html
{% extends 'store/nav.html' %}

{% block content %}

{% if errors %}
    <div>
      {% for error in errors %}
      {% autoescape off %}
        {{ error }}
      {% endautoescape %}
      {% endfor %}
    </div>
    {% endif %}

    <!-- Sidebar -->
    <div class="wrapper">
      <nav id="Sidebar">
        

        <ul class="list-unstyled components">
          <li class="active">
            <a data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
          </li>
        </ul>
      </nav>
    </div>
    <!-- Sidebar -->

  {% if items %}
    <!-- ITEMS DISPLAY-->
    <section>

        <hr class="mb-5">
        <hr class="mb-5">

        <!-- Grid row -->
        <div class="container">
        <div class="row">
            {% for item in items %}
              <!-- Grid column -->
                <div id="item-{{ forloop.counter }}" class="col-lg-3 col-md-6 mb-4 show">

                <!-- Card -->
                <div class="card card-ecommerce">
                  <!-- Card image -->
                  <div class="view overlay">
                    <img src="{{ item.img_one }}" class="img-fluid"
                      alt="sample image">

                    <a href="{% url 'store:items' item_id=item.id %}">
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>
                  <!-- Card image -->

                  <!-- Card content -->
                  <div class="card-body">
                    <!-- Category & Title -->
                    <h5 class="card-title mb-1">
                      <strong>
                        <a id="{{item.id}}-name" href="{% url 'store:items' item_id=item.id %}" class="dark-grey-text">{{ item.name }}</a>
                      </strong>
                    </h5>

                    {% if item.available %}
                    <span class="badge badge-danger mb-2">Displonible</span>
                    {% endif %}

                    <!-- Rating -->
                    <ul class="rating">
                      {% for i in '12345'|make_list %}
                        {% if item.rate >= forloop.counter %}
                          <li>
                            <i class="fas fa-star blue-text"></i>
                          </li>
                        {% else %}
                          <li>
                            <i class="fas fa-star grey-text"></i>
                          </li>
                          {% endif %}
                          {% endfor %}
                    </ul>

                    <!-- Card footer -->
                    <div class="card-footer pb-0">
                      <div class="row mb-0">
                        <span class="float-left">
                          <strong id="{{item.id}}-price">{{ item.price }}</strong><strong>$</strong>
                        </span>

                        <span class="float-right">
                          <a onclick="add_to_cart('{{item.id}}', '{{csrf_token}}')" 
                            class="" data-toggle="tooltip" data-placement="top" title="Add to Cart">
                            <i class="fas fa-shopping-cart ml-3"></i>
                          </a>
                        </span>
                      </div>
                    </div>
                  </div>
                  <!-- Card content -->
                </div>
                <!-- Card -->
              </div>
              <!-- Grid column -->
            {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}

{% endblock %}

CAC/store/templates/store/test_img.html
{% extends 'store/nav.html' %}
{% block content %}

    <hr>
    <hr>
    <hr>
    <hr>
    {% for key, value in session_data %}
        <p>{{key}}   {{value}}</p>
    {% endfor %}


{% endblock %}